[tool.black]
  line-length = 120

[tool.curlylint.rules]
  image_alt = true

[tool.mypy]
  files                       = "**/*.py"
  check_untyped_defs          = true
  disallow_untyped_defs       = true
  disallow_incomplete_defs    = true
  disallow_untyped_decorators = true
  warn_return_any             = true
  warn_unused_ignores         = true
  no_implicit_optional        = true
  show_error_codes            = true

[tool.ruff]
  line-length = 120
  target-version = "py310"
  fix = true
  unfixable = ["F401", "F841"]
  ignore = ["E711", "E712", "N805"]
  exclude = ["migrations"]
  select = [
    "F", # Pyflakes
    "E", # Pycodestyle
    "W", # Pycodestyle
    "I", # isort
    "B", # flake8-bugbear
    "Q", # flake8-quotes
    "D", # pydocstyle
    "N", # pep8-naming
    "UP", # pyupgrade
    "PL", # Pylint
  ]

[tool.ruff.pydocstyle]
  convention = "google"

[tool.ruff.mccabe]
  # Flag errors (`C901`) whenever the complexity level exceeds 5.
  max-complexity = 5

[tool.ruff.per-file-ignores]
"project/app/models/boost_customer.py" = ["F821"]
"project/app/models/agent.py" = ["F821"]
